/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuy_helloopengles_NativeRender */

#ifndef _Included_com_liuy_helloopengles_NativeRender
#define _Included_com_liuy_helloopengles_NativeRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuy_helloopengles_NativeRender
 * Method:    surfaceCreated
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_liuy_helloopengles_NativeRender_surfaceCreated
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_liuy_helloopengles_NativeRender
 * Method:    sufaceChange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_liuy_helloopengles_NativeRender_sufaceChange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_liuy_helloopengles_NativeRender
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liuy_helloopengles_NativeRender_onDrawFrame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
